syntax = "proto3";

package google.cloud.bigquery.storage.v1;

option java_package = "com.google.cloud.bigquery.storage.v1";
option java_outer_classname = "AvroProto";
option java_multiple_files = true;
option csharp_namespace = "Google.Cloud.BigQuery.Storage.V1";
option php_namespace = "Google\\Cloud\\BigQuery\\Storage\\V1";

import "google/api/auditing.proto";
import "storage/datapol/annotations/proto/semantic_annotations.proto";

message AvroSchema {
  string schema = 1;
}

message AvroRows {
  bytes serialized_binary_rows = 1;
  int64 row_count = 2;
}

message AvroSerializationOptions {
  enum PicosTimestampPrecision {
    PICOS_TIMESTAMP_PRECISION_UNSPECIFIED = 0;
    TIMESTAMP_PRECISION_MICROS = 1;
    TIMESTAMP_PRECISION_NANOS = 2;
    TIMESTAMP_PRECISION_PICOS = 3;
  }

  bool enable_display_name_attribute = 1;
  .google.cloud.bigquery.storage.v1.AvroSerializationOptions.PicosTimestampPrecision picos_timestamp_precision = 2;
}

